### ISSUE TITLE
Update EssentialsX to v2.17.2

### ISSUE THREAD

**Issue by Kranky916** [ego-tistical/di.mcserver.upgrade.test#21]
https://www.spigotmc.org/resources/essentialsx.9089/updates

**Comment by Kranky916** [comment]
Does EssentialsXChat and EssentialsXSpawn update with the new version or are they separate plugins?

**Comment by ego-tistical** [comment]
> Does EssentialsXChat and EssentialsXSpawn update with the new version or are they separate plugins?

Separate plugins, all downloaded
